# Generated by Django 4.2.5 on 2023-09-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('owner', 'Stadium Owner'), ('user', 'User')], default='user', max_length=5),
        ),
    ]
